{{- include "industrial-ops-application.validate" . -}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "industrial-ops-application.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
