{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "industrial-ops-release-controller.name" . }}
  namespace: {{ .Values.releaseNamespace }}
  labels:
    {{- include "industrial-ops-release-controller.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "industrial-ops-release-controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: ["Ingress", "Egress"]
  ingress: []
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 8181
        - protocol: TCP
          port: 9090
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
{{- end }}
