apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.releaseNamespace }}
  labels:
    {{- include "industrial-ops-release-controller.labels" . | nindent 4 }}
automountServiceAccountToken: true
