#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/harness_lock.sh"
change=; check=0; plan_check=0; as_json=0
while [[ $# -gt 0 ]]; do case "$1" in --check) check=1 ;; --plan-check) plan_check=1 ;; --json) as_json=1 ;; *) [[ -z "$change" ]] || exit 2; change=$1 ;; esac; shift; done
(( check + plan_check <= 1 )) || { echo '[ERR] --check and --plan-check are mutually exclusive' >&2; exit 2; }
requested=$change; [[ -z "$requested" ]] || harness_validate_change_id "$requested"; purpose=footprint; [[ "$check" -eq 0 ]] || purpose=footprint-check; [[ "$plan_check" -eq 0 ]] || purpose=footprint-plan-check; harness_lock_acquire "$purpose" "$requested"
if [[ "$check" -eq 0 && "$plan_check" -eq 0 ]]; then harness_require_no_archive_failure; fi
if [[ -n "$requested" && ( "$check" -eq 1 || "$plan_check" -eq 1 ) ]]; then harness_validate_change_id "$requested"; change=$requested; else change=$(harness_resolve_change "$requested"); fi
harness_lock_bind_change "$change"
dir="openspec/changes/$change"; snapshot="$dir/harness/ai_snapshot.json"; design="$dir/design.md"; report="$dir/harness/change-footprint.json"; [[ -f "$snapshot" && ! -L "$snapshot" && -f "$design" && ! -L "$design" ]] || { echo "[ERR] design and local snapshot required" >&2; exit 6; }
plan_snapshot=; runtime_snapshot=$snapshot
if [[ "$plan_check" -eq 1 ]]; then
  head_commit=$(git rev-parse --verify HEAD 2>/dev/null) || { echo '[ERR] planning readiness requires a HEAD commit' >&2; exit 4; }
  plan_snapshot=$(mktemp "${TMPDIR:-/tmp}/autoai-plan-snapshot.XXXXXX")
  node - "$snapshot" "$plan_snapshot" "$head_commit" <<'NODE'
const fs=require('fs');const [src,out,head]=process.argv.slice(2),d=JSON.parse(fs.readFileSync(src));if(![2,3,4].includes(d.schema_version)||'active_change'in d)process.exit(6);if(d.implementation_base_commit===null)d.implementation_base_commit=head;else if(typeof d.implementation_base_commit!=='string'||!/^[0-9a-f]{40,64}$/.test(d.implementation_base_commit))process.exit(6);fs.writeFileSync(out,JSON.stringify(d));
NODE
  runtime_snapshot=$plan_snapshot
fi
if [[ "$check" -eq 1 || "$plan_check" -eq 1 ]]; then tmp=$(mktemp "${TMPDIR:-/tmp}/autoai-footprint.XXXXXX"); else mkdir -p "$(dirname "$report")"; tmp=$(mktemp "$(dirname "$report")/.footprint.XXXXXX"); fi; trap 'rm -f -- "$tmp" "$plan_snapshot"; harness_lock_release' EXIT
node - "$change" "$runtime_snapshot" "$design" "$tmp" <<'NODE' || { echo '[ERR] footprint contract or accounting failed' >&2; exit 6; }
const fs=require('fs'),path=require('path'),cp=require('child_process'),crypto=require('crypto'),{TextDecoder}=require('util');const [change,snapshotFile,designFile,out]=process.argv.slice(2),fail=m=>{throw Error(m)},sha=b=>'sha256:'+crypto.createHash('sha256').update(b).digest('hex'),utf8=new TextDecoder('utf-8',{fatal:true}),decode=(b,w)=>{try{return utf8.decode(b)}catch{fail(w+' is not valid UTF-8')}};
function parse(src){let i=0;const ws=()=>{while(/\s/.test(src[i]||''))i++};function str(){const s=i++;for(;i<src.length;i++){if(src[i]==='\\'){i++;continue}if(src[i]==='"'){i++;return JSON.parse(src.slice(s,i))}}fail('unterminated JSON string')}function val(){ws();const c=src[i];if(c==='"')return str();if(c==='{'){i++;const o={},seen=new Set;ws();if(src[i]==='}'){i++;return o}for(;;){ws();if(src[i]!=='"')fail('JSON key expected');const k=str();if(seen.has(k))fail('duplicate JSON key: '+k);seen.add(k);ws();if(src[i++]!==':')fail('colon expected');o[k]=val();ws();const d=src[i++];if(d==='}')return o;if(d!==',')fail('comma expected')}}if(c==='['){i++;const a=[];ws();if(src[i]===']'){i++;return a}for(;;){a.push(val());ws();const d=src[i++];if(d===']')return a;if(d!==',')fail('comma expected')}}const m=src.slice(i).match(/^(true|false|null|-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?)/);if(!m)fail('invalid JSON');i+=m[0].length;return JSON.parse(m[0])}const v=val();ws();if(i!==src.length)fail('trailing JSON');return v}
const cmp=(a,b)=>{const x=Array.from(a),y=Array.from(b);for(let i=0;i<Math.min(x.length,y.length);i++){const d=x[i].codePointAt(0)-y[i].codePointAt(0);if(d)return d}return x.length-y.length},canon=v=>Array.isArray(v)?'['+v.map(canon).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort(cmp).map(k=>JSON.stringify(k)+':'+canon(v[k])).join(',')+'}':JSON.stringify(v);
const text=decode(fs.readFileSync(designFile),'design.md'),economyVariants=[
  {version:1,start:'<!-- autoai:implementation-economy:v1 -->',end:'<!-- /autoai:implementation-economy:v1 -->'},
  {version:2,start:'<!-- autoai:implementation-economy:v2 -->',end:'<!-- /autoai:implementation-economy:v2 -->'}
],present=economyVariants.filter(x=>text.includes(x.start)||text.includes(x.end));if(present.length!==1)fail('exactly one supported Implementation Economy block required');const marker=present[0];if(text.split(marker.start).length!==2||text.split(marker.end).length!==2)fail('Implementation Economy markers must occur exactly once');const body=text.slice(text.indexOf(marker.start)+marker.start.length,text.indexOf(marker.end)),m=body.match(/^\s*```json\s*\n([\s\S]*?)\n```\s*$/);if(!m)fail('economy block must contain one JSON fence');const b=parse(m[1]);if(b.schema_version!==marker.version)fail('Implementation Economy marker/schema mismatch');
const allowed=(o,a,w)=>{if(!o||typeof o!=='object'||Array.isArray(o))fail(w+' object required');for(const k of Object.keys(o))if(!a.includes(k))fail(`${w}: unknown ${k}`)};
allowed(b,['schema_version','profile','rationale','classification','thresholds','structural_allowances','reuse_decisions','obsolete_items','exceptions'],'budget');if(![1,2].includes(b.schema_version)||!['micro','small','medium','large'].includes(b.profile)||typeof b.rationale!=='string'||!b.rationale.trim())fail('invalid budget header');
const classes=['production','tests','project_docs','project_tooling','examples','generated','vendor'];allowed(b.classification,classes,'classification');for(const c of classes)if(!Array.isArray(b.classification[c]))fail(`classification.${c} array required`);
const nonempty=(v,w)=>{if(typeof v!=='string'||!v.trim())fail(w+' must be non-empty');return v},secret=/(?:authorization|proxy-authorization|bearer|x-?api-?key|api[_-]?key|token|password|secret|cookie|client[_-]?secret|private[_-]?key|access[_-]?key)[\s:=]+\S+|:\/\/[^/\s:]+:[^/@\s]+@|-----BEGIN [A-Z ]*PRIVATE KEY-----/i,credentialOptions=new Set(['--token','--password','--secret','--api-key','--apikey','-H','--header','--cookie']);
function safePattern(v,w){nonempty(v,w);if(v.includes('\0')||v.includes('\n')||v.includes('\r')||v.includes('\\')||v.startsWith('/')||/^[A-Za-z]:/.test(v)||v.startsWith(':')||v.startsWith('!'))fail(w+' is not a safe repository path pattern');const probe=v.replace(/[?*]+/g,'x'),norm=path.posix.normalize(probe);if(norm==='..'||norm.startsWith('../')||norm.startsWith('.git/')||norm==='.git')fail(w+' escapes or targets Git metadata');return v}
for(const c of classes){for(const [i,x] of b.classification[c].entries()){if(c==='generated'){allowed(x,['output','inputs','argv'],`classification.generated[${i}]`);safePattern(x.output,`generated[${i}].output`);if(!Array.isArray(x.inputs)||!x.inputs.length||!x.inputs.every((p,j)=>{safePattern(p,`generated[${i}].inputs[${j}]`);return true})||!Array.isArray(x.argv)||!x.argv.length||x.argv.some(a=>typeof a!=='string'||!a||a.includes('\0')||credentialOptions.has(a)||secret.test(a)))fail('generated entries require safe output, non-empty inputs and secret-free argv')}else{if(typeof x!=='string')fail(`${c} classification entries must be strings`);safePattern(x,`classification.${c}[${i}]`)}}}
const groups={production:['added_lines','touched_files','new_files'],tests:['added_lines','touched_files','new_files'],project_support:['added_lines','new_files'],generated:['files','bytes']};allowed(b.thresholds,Object.keys(groups),'thresholds');for(const [g,ms]of Object.entries(groups)){allowed(b.thresholds[g],ms,g);for(const metric of ms){const t=b.thresholds[g][metric];allowed(t,['expected','review_at','hard_limit'],`${g}.${metric}`);if(!Number.isInteger(t.expected)||!Number.isInteger(t.review_at)||!Number.isInteger(t.hard_limit)||t.expected<0||t.expected>t.review_at||t.review_at>t.hard_limit)fail('non-monotonic threshold')}}
const allowanceFields=b.schema_version===1?['public_contracts','cmake_targets','direct_dependencies']:['public_contracts','build_targets','build_graph_entries','distribution_surfaces','direct_dependencies'];allowed(b.structural_allowances,allowanceFields,'structural_allowances');if(allowanceFields.some(k=>!Object.prototype.hasOwnProperty.call(b.structural_allowances,k)))fail('structural_allowances is incomplete');const ids=new Set,register=(x,w)=>{if(!x||typeof x.id!=='string'||!x.id.trim()||ids.has(x.id))fail('missing or duplicate budget item ID at '+w);ids.add(x.id)};
for(const [kind,list] of Object.entries(b.structural_allowances)){if(!Array.isArray(list))fail('budget list missing: '+kind);for(const [i,x] of list.entries()){allowed(x,['id','name','reason'],`${kind}[${i}]`);register(x,kind);nonempty(x.name,kind+' name');nonempty(x.reason,kind+' reason')}}
if(!Array.isArray(b.reuse_decisions))fail('reuse_decisions array required');for(const [i,x] of b.reuse_decisions.entries()){allowed(x,['id','path','symbol','decision','reason'],`reuse_decisions[${i}]`);register(x,'reuse');safePattern(x.path,'reuse path');nonempty(x.symbol,'reuse symbol');if(!['reuse','extend','reject'].includes(x.decision))fail('invalid reuse decision');nonempty(x.reason,'reuse reason')}
if(!Array.isArray(b.obsolete_items))fail('obsolete_items array required');for(const [i,x] of b.obsolete_items.entries()){allowed(x,['id','path','symbol','disposition','reason','exit_condition','task_or_debt'],`obsolete_items[${i}]`);register(x,'obsolete');safePattern(x.path,'obsolete path');nonempty(x.symbol,'obsolete symbol');if(!['delete','deprecate','retain'].includes(x.disposition))fail('invalid obsolete disposition');nonempty(x.reason,'obsolete reason');if(x.disposition==='delete'){if('exit_condition'in x&&x.exit_condition!==null||'task_or_debt'in x&&x.task_or_debt!==null)fail('delete disposition must not carry a future exit')}else{nonempty(x.exit_condition,'obsolete exit_condition');nonempty(x.task_or_debt,'obsolete task_or_debt')}}
if(!Array.isArray(b.exceptions))fail('exceptions array required');for(const [i,x] of b.exceptions.entries()){allowed(x,['id','metric','paths','reason','requirement_refs','task_ids','verification'],`exceptions[${i}]`);register(x,'exception');nonempty(x.metric,'exception metric');if(!Array.isArray(x.paths)||!x.paths.length||!x.paths.every((p,j)=>{safePattern(p,`exception[${i}].paths[${j}]`);return true})||!Array.isArray(x.requirement_refs)||!x.requirement_refs.length||x.requirement_refs.some(v=>typeof v!=='string'||!v.trim())||!Array.isArray(x.task_ids)||!x.task_ids.length||x.task_ids.some(v=>typeof v!=='string'||!/^\d+(?:\.\d+)*$/.test(v)))fail('exception references are incomplete');nonempty(x.reason,'exception reason');nonempty(x.verification,'exception verification')}
const snap=JSON.parse(fs.readFileSync(snapshotFile)),base=snap.implementation_base_commit;if(typeof base!=='string'||!/^[0-9a-f]{40,64}$/.test(base))fail('full implementation_base_commit must be frozen');try{cp.execFileSync('git',['merge-base','--is-ancestor',base,'HEAD'])}catch{fail('implementation base is not an ancestor of HEAD')}
function glob(g){let s='^';for(let i=0;i<g.length;i++){const c=g[i];if(c==='*'&&g[i+1]==='*'){const segmentStart=i===0||g[i-1]==='/';if(segmentStart&&g[i+2]==='/'){s+='(?:.*/)?';i+=2}else if(segmentStart&&i+2===g.length){s+='.*';i++}else{s+='[^/]*';i++}}else if(c==='*')s+='[^/]*';else if(c==='?')s+='[^/]';else{s+='\\.^$+{}()|[]'.includes(c)?'\\'+c:c}}return new RegExp(s+'$')}
const git=a=>cp.execFileSync('git',a),scope=require(process.cwd()+'/scripts/change_scope.js').collectScope(process.cwd(),base,b.classification,b.schema_version,Array.isArray(snap.adopted_preexisting_paths)?snap.adopted_preexisting_paths:[]),changes=scope.metric_changes,buckets=scope.buckets,unclassified=scope.unclassified_paths,overlaps=scope.classification_overlaps,binary=changes.filter(x=>x.added===null),patterns={};for(const c of classes)patterns[c]=b.classification[c].map(x=>({re:glob(typeof x==='string'?x:x.output)}));
const isNew=p=>{try{cp.execFileSync('git',['cat-file','-e',`${base}:${p}`]);return false}catch{return true}},stats=a=>({added_lines:a.reduce((n,x)=>n+(x.added||0),0),deleted_lines:a.reduce((n,x)=>n+(x.deleted||0),0),net_lines:a.reduce((n,x)=>n+(x.added||0)-(x.deleted||0),0),touched_files:a.length,new_files:a.filter(x=>isNew(x.path)).length});
const prod=stats(buckets.production),test=stats(buckets.tests),supportList=[...buckets.project_docs,...buckets.project_tooling,...buckets.examples],support=stats(supportList),generated={files:buckets.generated.length,bytes:buckets.generated.reduce((n,x)=>n+(fs.existsSync(x.path)?fs.lstatSync(x.path).size:0),0)},values={production:prod,tests:test,project_support:support,generated},rank={within_expected:0,drift_warning:1,review_required:2,hard_exceeded:3,invalid:4};let status='within_expected';
for(const [g,ms]of Object.entries(groups))for(const metric of ms){const actual=values[g][metric],t=b.thresholds[g][metric],s=actual<=t.expected?'within_expected':actual>t.hard_limit?'hard_exceeded':actual>=t.review_at?'review_required':'drift_warning';if(rank[s]>rank[status])status=s}const unapprovedBinary=binary.filter(p=>!b.exceptions.some(x=>(x.metric==='binary'||x.metric===`binary:${p.path}`)&&x.paths.some(q=>glob(q).test(p.path))));if(unclassified.length||overlaps.length||unapprovedBinary.length)status='invalid';
const binarySize=x=>{try{const st=fs.lstatSync(x.path);if(st.isFile()&&!st.isSymbolicLink())return st.size}catch{}try{return Number(cp.execFileSync('git',['cat-file','-s',`${base}:${x.path}`],{encoding:'utf8'}).trim())||0}catch{return 0}},binaryReport={files:binary.length,bytes:binary.reduce((n,x)=>n+binarySize(x),0),paths:binary.map(x=>x.path)};
const source=JSON.parse(cp.execFileSync('scripts/source_fingerprint.sh',['--kind','source','--json'],{encoding:'utf8'})).source_fingerprint,structural=scope.structural_candidates.map(x=>({candidate_id:x.candidate_id,path:x.path,kind:x.kind,allowance_kind:x.allowance_kind}));
const report={schema_version:1,change_name:change,implementation_base_commit:base,source_fingerprint:source,budget_block_sha256:sha(Buffer.from(canon(b))),status,production:prod,tests:{added_lines:test.added_lines,touched_files:test.touched_files,new_files:test.new_files},project_support:{added_lines:support.added_lines,touched_files:support.touched_files,new_files:support.new_files,paths_by_class:{project_docs:buckets.project_docs.map(x=>x.path),project_tooling:buckets.project_tooling.map(x=>x.path),examples:buckets.examples.map(x=>x.path)}},generated,vendor:{changed_paths:buckets.vendor.map(x=>x.path)},binary:binaryReport,structural_candidates:structural,unclassified_paths:unclassified,classification_overlaps:overlaps};fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');
NODE
if [[ "$check" -eq 1 ]]; then [[ -f "$report" ]] && cmp -s "$tmp" "$report" || { echo "[ERR] footprint report missing, stale or modified" >&2; exit 6; }; elif [[ "$plan_check" -eq 0 ]]; then mkdir -p "$(dirname "$report")"; mv -f -- "$tmp" "$report"; fi
result_file=$report; [[ "$plan_check" -eq 0 ]] || result_file=$tmp
status=$(node -p "JSON.parse(require('fs').readFileSync(process.argv[1])).status" "$result_file"); [[ "$as_json" -eq 0 ]] && echo "$status" || cat "$result_file"; case "$status" in within_expected|drift_warning) exit 0 ;; *) exit 6 ;; esac
