#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/harness_lock.sh"
[[ $# -le 1 ]] || exit 2; requested=${1:-}; [[ -z "$requested" ]] || harness_validate_change_id "$requested"; harness_lock_acquire archive "$requested"; harness_require_no_archive_failure; change=$(harness_resolve_change "$requested"); harness_lock_bind_change "$change"; source_dir="openspec/changes/$change"; [[ -d "$source_dir" && ! -L "$source_dir" ]] || { echo '[ERR] active change is stale or archived' >&2; exit 4; }
scripts/attribution_check.sh --quiet || { echo '[ERR] project attribution contract is invalid; archive was not invoked' >&2; exit 6; }
harness_verification_workspace_control cleanup "$change" || { echo '[ERR] temporary verification program cleanup failed; archive was not invoked' >&2; exit 6; }
harness_verification_workspace_control assert-clean "$change" || { echo '[ERR] temporary verification workspace is not clean; archive was not invoked' >&2; exit 6; }
harness_prepare_runtime_dir logs || { echo '[ERR] unsafe archive log directory' >&2; exit 4; }; stamp=$(date -u +%Y%m%dT%H%M%SZ); target="openspec/changes/archive/$(date -u +%Y-%m-%d)-$change"; log=$(mktemp ".ai-harness/logs/archive-$change-$stamp.XXXXXX.log"); transaction=.ai-harness/archive-transaction.json; exec 3>>"$log"
ins=$(mktemp); val=$(mktemp); out=$(mktemp); err=$(mktemp); fp=$(mktemp); evidence=$(mktemp); preflight=$(mktemp); recovery_out=$(mktemp); recovery_err=$(mktemp); locations=$(mktemp); candidates=$(mktemp); actual_dir=
trap 'rm -f -- "$ins" "$val" "$out" "$err" "$fp" "$evidence" "$preflight" "$recovery_out" "$recovery_err" "$locations" "$candidates"; harness_lock_release' EXIT
printf 'change=%s\nstarted_at=%s\nutc_target=%s\n' "$change" "$stamp" "$target" >&3
log_repo_state(){
  local phase=$1 diff_hash
  printf '\n[%s.git-status]\n' "$phase" >&3
  git status --short --untracked-files=all >&3 2>&1 || true
  printf '[%s.git-name-status]\n' "$phase" >&3
  git diff --no-ext-diff --name-status -- >&3 2>&1 || true
  diff_hash=$(git diff --no-ext-diff --binary -- 2>/dev/null | sha256sum | awk '{print $1}' || true)
  printf '[%s.git-diff-sha256]\n%s\n' "$phase" "${diff_hash:-unavailable}" >&3
}
refresh_actual_locations(){
  : > "$candidates"; find openspec/changes/archive -mindepth 1 -maxdepth 1 -name "*-$change" -print0 > "$candidates" 2>/dev/null || true
  actual_dir=$(node - "$out" <<'NODE' 2>/dev/null || true
const fs=require('fs'),path=require('path');try{const v=JSON.parse(fs.readFileSync(process.argv[2])),p=v?.archive?.path,root=path.resolve('openspec/changes/archive');if(typeof p!=='string'||!path.isAbsolute(p))process.exit(0);const r=path.resolve(p);if(r!==root&&!r.startsWith(root+path.sep))process.exit(0);process.stdout.write(path.relative(process.cwd(),r).split(path.sep).join('/'))}catch{}
NODE
  )
  node - "$change" "$target" "$actual_dir" "$candidates" > "$locations" <<'NODE'
const fs=require('fs'),path=require('path');const [change,target,actual,candidates]=process.argv.slice(2),kind=p=>{try{const s=fs.lstatSync(p);return s.isSymbolicLink()?'symlink':s.isDirectory()?'directory':s.isFile()?'file':'other'}catch(e){if(e.code==='ENOENT')return'missing';throw e}},rows=fs.readFileSync(candidates).toString('utf8').split('\0').filter(Boolean).map(p=>({path:p.split(path.sep).join('/'),kind:kind(p)}));console.log(JSON.stringify({main_specs:{path:'openspec/specs',kind:kind('openspec/specs')},source_change:{path:`openspec/changes/${change}`,kind:kind(`openspec/changes/${change}`)},utc_archive:{path:target,kind:kind(target)},actual_archive:actual?{path:actual,kind:kind(actual)}:null,archive_candidates:rows},null,2));
NODE
  printf '\n[recovery.actual-locations]\n' >&3; cat "$locations" >&3
}
diagnose_validate(){ local label=$1 mode=$2 item=${3:-} rc clean; : > "$recovery_out"; : > "$recovery_err"; set +e; if [[ "$mode" == specs ]]; then scripts/openspec_cli.sh validate --specs --strict --json --no-interactive >"$recovery_out" 2>"$recovery_err"; else scripts/openspec_cli.sh validate "$item" --type change --strict --json --no-interactive >"$recovery_out" 2>"$recovery_err"; fi; rc=$?; node - "$recovery_out" <<'NODE' >/dev/null 2>&1
const fs=require('fs');try{const v=JSON.parse(fs.readFileSync(process.argv[2])),failed=v?.summary?.totals?.failed;if(!Number.isInteger(failed)||failed!==0)process.exit(1);function bad(x){if(!x||typeof x!=='object')return false;if(x.valid===false||Array.isArray(x.issues)&&x.issues.some(i=>String(i?.level||'').toUpperCase()==='ERROR'))return true;return Object.values(x).some(bad)}if(bad(v))process.exit(1)}catch{process.exit(1)}
NODE
  clean=$?; set -e; printf '\n[recovery.strict-validation.%s]\ncommand_rc=%s\njson_clean=%s\nstdout:\n' "$label" "$rc" "$([[ "$clean" -eq 0 ]] && echo true || echo false)" >&3; cat "$recovery_out" >&3; printf '\nstderr:\n' >&3; cat "$recovery_err" >&3; }
diagnose_archived_location(){ local p=$1; printf '\n[recovery.strict-validation.archive-%s]\nnot_applicable=true\nreason=OpenSpec validates active change IDs, not archived directory paths; main specs and retained evidence are checked separately.\n' "$(basename "$p")" >&3; }
diagnose_failure_locations(){ local p; declare -A seen=(); refresh_actual_locations; diagnose_validate main-specs specs; if [[ -d "$source_dir" && ! -L "$source_dir" ]]; then diagnose_validate source-change change "$change"; fi; for p in "$target" "$actual_dir"; do [[ -n "$p" && -d "$p" && ! -L "$p" && -z "${seen[$p]:-}" ]] || continue; seen[$p]=1; diagnose_archived_location "$p"; done; while IFS= read -r -d '' p; do [[ -d "$p" && ! -L "$p" && -z "${seen[$p]:-}" ]] || continue; seen[$p]=1; diagnose_archived_location "$p"; done < "$candidates"; }
reject_archive(){ local m=$1; printf '\n[gate-rejection]\nmessage=%s\nrejected_at=%s\n' "$m" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >&3; log_repo_state gate-rejection; echo "[ERR] $m. Archive was not invoked; fix the failed gate and continue the normal workflow. Log: $log" >&2; exit 6; }
fail_archive(){ local m=$1 snapshot_rc=0; printf '\n[failure]\nmessage=%s\nfailed_at=%s\n' "$m" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >&3; set +e; diagnose_failure_locations; node - "$change" "$m" "$locations" "$log" <<'NODE' || snapshot_rc=$?
const fs=require('fs'),path=require('path');const [c,m,locationsFile,log]=process.argv.slice(2),f='ai_snapshot.json',d=JSON.parse(fs.readFileSync(f)),actual=JSON.parse(fs.readFileSync(locationsFile));
if(d.schema_version!==2||d.workflow!=='openspec'||d.archive_failure!==undefined&&d.archive_failure!==null)process.exit(1);
const sourcePresent=actual.source_change?.kind==='directory';if(d.active_change===c&&!sourcePresent)d.active_change=null;
d.phase='archive_failed';d.current_step='archive-partial-failure';d.next_step='Inspect archive log and all recorded OpenSpec locations; do not retry automatically';d.archive_failure={change:c,message:m,recorded_at:new Date().toISOString().replace('.000Z','Z'),active_cleared:d.active_change===null&&!sourcePresent,actual_locations:actual,log_path:log};d.updated_at=d.archive_failure.recorded_at;
let t;for(let i=0;i<20;i++){t=path.join(path.dirname(f),`.snapshot-archive-${process.pid}-${i}`);try{const fd=fs.openSync(t,'wx',0o644);fs.writeFileSync(fd,JSON.stringify(d,null,2)+'\n');fs.fsyncSync(fd);fs.closeSync(fd);fs.renameSync(t,f);const dir=fs.openSync(path.dirname(f)||'.','r');fs.fsyncSync(dir);fs.closeSync(dir);t=null;break}catch(e){if(e.code!=='EEXIST')throw e}}if(t)throw Error('cannot allocate atomic snapshot temp');
NODE
  if [[ "$snapshot_rc" -ne 0 ]]; then printf '\n[emergency-marker]\nroot_snapshot_update_rc=%s\nprepared_transaction=%s\n' "$snapshot_rc" "$transaction" >&3; fi; log_repo_state post-failure; set -e; echo "[ERR] $m. Archive is non-transactional; the prepared transaction remains a global recovery gate. Preserve state and inspect $log" >&2; exit 6; }
node - ai_snapshot.json "$change" <<'NODE' || reject_archive 'fresh independent Evaluation required after source-retained archive recovery'
const fs=require('fs');const [file,change]=process.argv.slice(2),d=JSON.parse(fs.readFileSync(file)),a=d.last_archive_recovery_acknowledgment;if(d.phase==='archive_recovery_acknowledged'&&a?.change_name===change&&a?.recovered_state==='source-retained')process.exit(1);
NODE
if ! scripts/openspec_preflight.sh >"$preflight" 2>&1; then printf '\n[openspec-preflight]\n' >&3; cat "$preflight" >&3; reject_archive 'fixed OpenSpec preflight failed'; fi; printf '\n[openspec-preflight]\n' >&3; cat "$preflight" >&3
scripts/openspec_cli.sh instructions apply --change "$change" --json > "$ins" || reject_archive 'instructions failed'
node - "$ins" "$change" <<'NODE' || reject_archive 'tasks incomplete or instructions JSON contract mismatch'
const fs=require('fs'),r=JSON.parse(fs.readFileSync(process.argv[2])),p=r?.progress,t=r?.tasks;if(r?.changeName!==process.argv[3]||r?.schemaName!=='spec-driven'||r?.state!=='all_done'||!p||!Number.isInteger(p.total)||!Number.isInteger(p.complete)||!Number.isInteger(p.remaining)||p.total<=0||p.complete!==p.total||p.remaining!==0||!Array.isArray(t)||t.length!==p.total)process.exit(1);const ids=new Set;for(const x of t){if(!x||typeof x.id!=='string'||!x.id||ids.has(x.id)||x.done!==true)process.exit(1);ids.add(x.id)}
NODE
scripts/openspec_cli.sh validate "$change" --type change --strict --json --no-interactive > "$val" || reject_archive 'strict change validation failed'
node - "$val" "$change" <<'NODE' || reject_archive 'strict validation JSON has errors'
const fs=require('fs'),v=JSON.parse(fs.readFileSync(process.argv[2])),change=process.argv[3],items=v?.items,failed=v?.summary?.totals?.failed;function hasError(x){if(!x||typeof x!=='object')return false;if(Array.isArray(x.issues)&&x.issues.some(i=>String(i?.level||'').toUpperCase()==='ERROR'))return true;return Object.values(x).some(hasError)}if(!Array.isArray(items)||items.length!==1||items[0]?.id!==change||items[0]?.valid!==true||!Number.isInteger(failed)||failed!==0||hasError(v))process.exit(1);
NODE
AUTOAI_LOCK_TOKEN="$HARNESS_OWNED_TOKEN" AUTOAI_PARENT_PURPOSE=archive scripts/change_footprint.sh "$change" --check --json >/dev/null || reject_archive 'footprint stale or blocked'
snapshot_schema=$(node -p "JSON.parse(require('fs').readFileSync(process.argv[1])).schema_version" "$source_dir/harness/ai_snapshot.json" 2>/dev/null || true)
if [[ "$snapshot_schema" == 4 ]]; then AUTOAI_LOCK_TOKEN="$HARNESS_OWNED_TOKEN" AUTOAI_PARENT_PURPOSE=archive scripts/integration_surface_check.sh "$change" --check --json >/dev/null || reject_archive 'Integration Completeness report is orphaned, blocked, missing or stale'; fi
baseline="openspec/changes/$change/harness/evaluation-baseline.json"; evaluation="openspec/changes/$change/harness/evaluation.json"; [[ -f "$baseline" && -f "$evaluation" && "$(node -p "JSON.parse(require('fs').readFileSync(process.argv[1])).status" "$baseline")" == complete ]] || reject_archive 'complete Evaluation missing'
AUTOAI_LOCK_TOKEN="$HARNESS_OWNED_TOKEN" AUTOAI_PARENT_PURPOSE=archive scripts/evaluator_check.sh --finish "$change" >/dev/null || reject_archive 'complete Evaluation recheck failed'
node - "$baseline" "$evaluation" "$change" "$source_dir/harness/evaluation-command-ledger.json" "$source_dir/harness/integration-surface-report.json" <<'NODE' || reject_archive 'Evaluation is not a digest-bound Pass or is not Integration-complete'
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const [bf,ef,c,ledgerFile,reportFile]=process.argv.slice(2),b=JSON.parse(fs.readFileSync(bf)),e=JSON.parse(fs.readFileSync(ef)),h='sha256:'+crypto.createHash('sha256').update(fs.readFileSync(ef)).digest('hex'),canon=v=>Array.isArray(v)?'['+v.map(canon).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canon(v[k])).join(',')+'}':JSON.stringify(v),sha=v=>'sha256:'+crypto.createHash('sha256').update(canon(v)).digest('hex'),legacy=b.schema_version===1&&e.schema_version===1,modern=b.schema_version===2&&e.schema_version===2,integrated=b.schema_version===3&&e.schema_version===3;
if(!legacy&&!modern&&!integrated||b.status!=='complete'||b.evaluation_json_sha256!==h||e.change_name!==c||e.evaluation_id!==b.evaluation_id||e.openspec_version!=='1.6.0'||e.verdict!=='Pass'||e.implementation_economy?.result!=='Pass'||!Array.isArray(e.blocking_untested)||e.blocking_untested.length)process.exit(1);
if(!legacy){const copy=path.join(path.dirname(ef),'evaluations',`${e.evaluation_id}.json`);let x=null,raw=null;try{raw=fs.readFileSync(copy);x=JSON.parse(raw)}catch{}if(!Array.isArray(e.change_review?.stages)||e.change_review.stages.length!==2||e.change_review.stages.some(item=>item.status!=='Pass')||e.change_review.findings?.some(item=>item.status==='Open'&&['Critical','Important'].includes(item.severity))||!x||!raw.equals(Buffer.from(JSON.stringify(x,null,2)+'\n'))||fs.lstatSync(copy).isSymbolicLink()||!fs.lstatSync(copy).isFile()||x.envelope_schema_version!==1||x.terminal_status!=='complete'||x.source_schema_version!==b.schema_version||x.evaluation_id!==e.evaluation_id||x.change_name!==c||x.baseline_sha256!==sha(b)||x.evaluation_sha256!==sha(e)||canon(x.baseline)!==canon(b)||canon(x.evaluation)!==canon(e))process.exit(1)}
if(integrated){const ledger=JSON.parse(fs.readFileSync(ledgerFile)),reportRaw=fs.readFileSync(reportFile),report=JSON.parse(reportRaw),v=require(process.cwd()+'/scripts/integration_surface_lib.js').validateEvaluationV3({root:process.cwd(),change:c,baseline:b,evaluation:e,ledger,report,report_raw:reportRaw});if(v.result!=='Pass'||e.integration_completeness?.inventory_assessment?.result!=='Pass'||e.integration_completeness?.orphan_surfaces?.length||e.integration_completeness?.surface_assessments?.some(a=>a.result!=='Pass')||e.integration_completeness?.candidate_assessments?.some(a=>a.disposition==='orphan'))process.exit(1)}
NODE
scripts/source_fingerprint.sh --kind all --change "$change" --json > "$fp" || reject_archive 'pre-archive fingerprint failed'; printf '\n[pre-archive.fingerprints]\n' >&3; cat "$fp" >&3
node - "$fp" "$source_dir/harness/change-footprint.json" "$baseline" "$evaluation" "$source_dir/harness/verification.json" "$source_dir/harness/integration-surface-report.json" > "$evidence" <<'NODE' || reject_archive 'pre-archive fingerprints or digest-bound evidence changed after Evaluation recheck'
const fs=require('fs'),crypto=require('crypto');
const [fpFile,footFile,baselineFile,evaluationFile,verificationFile,reportFile]=process.argv.slice(2),read=p=>JSON.parse(fs.readFileSync(p)),sha=p=>'sha256:'+crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),fp=read(fpFile),foot=read(footFile),evaluation=read(evaluationFile),baseline=read(baselineFile),digest=v=>typeof v==='string'&&/^sha256:[0-9a-f]{64}$/.test(v);
if(!fp||Object.keys(fp).length!==4||!digest(fp.profile_sha256)||!['source_fingerprint','artifact_fingerprint','base_specs_fingerprint'].every(k=>digest(fp[k])&&fp[k]===baseline[k]&&evaluation[k]===baseline[k])||baseline.status!=='complete'||baseline.verification_json_sha256!==sha(verificationFile)||baseline.change_footprint_json_sha256!==sha(footFile)||baseline.evaluation_json_sha256!==sha(evaluationFile)||evaluation.change_footprint_json_sha256!==baseline.change_footprint_json_sha256||evaluation.budget_block_sha256!==baseline.budget_block_sha256||foot.budget_block_sha256!==baseline.budget_block_sha256)process.exit(1);
if(baseline.schema_version===3&&baseline.integration_surface_report_sha256!==sha(reportFile))process.exit(1);
const groups=['production','tests','project_support','generated'],counts={};for(const g of groups){const x=foot[g];if(x&&typeof x==='object')counts[g]=Object.fromEntries(Object.entries(x).filter(([,n])=>Number.isFinite(n)))}
console.log(JSON.stringify({fingerprints:fp,budget_block_sha256:foot.budget_block_sha256,verification_json_sha256:sha(verificationFile),change_footprint_json_sha256:sha(footFile),evaluation_baseline_json_sha256:sha(baselineFile),evaluation_json_sha256:sha(evaluationFile),integration_surface_report_sha256:baseline.schema_version===3?sha(reportFile):null,footprint:{status:foot.status,counts},evaluation:{evaluation_id:evaluation.evaluation_id,verdict:evaluation.verdict,evaluated_at:evaluation.evaluated_at,baseline_status:baseline.status}},null,2));
NODE
printf '\n[pre-archive.evidence]\n' >&3; cat "$evidence" >&3
while IFS= read -r -d '' f; do [[ "$(node -p "JSON.parse(require('fs').readFileSync(process.argv[1])).status" "$f" 2>/dev/null||echo invalid)" == complete ]] || reject_archive "pending migration recovery: $f"; done < <(find .ai-harness/migrations -mindepth 2 -maxdepth 2 -name manifest.json -print0 2>/dev/null)
[[ ! -e "$target" && ! -L "$target" && -d openspec/changes/archive && ! -L openspec/changes/archive && -w openspec/changes/archive ]] || reject_archive 'UTC archive target changed after preflight, conflicts, or is a dangling symlink'
node - "$transaction" "$change" "$target" "$log" "$fp" "$evidence" ai_snapshot.json <<'NODE' || reject_archive 'could not durably prepare the archive transaction journal'
const fs=require('fs'),path=require('path'),crypto=require('crypto');const [file,change,target,log,fpFile,evidenceFile,snapshotFile]=process.argv.slice(2),sha=b=>'sha256:'+crypto.createHash('sha256').update(b).digest('hex'),fingerprints=JSON.parse(fs.readFileSync(fpFile)),now=new Date().toISOString().replace('.000Z','Z');
let prior=null;try{const st=fs.lstatSync(file);if(!st.isFile()||st.isSymbolicLink())throw Error('unsafe prior archive transaction');prior=JSON.parse(fs.readFileSync(file))}catch(e){if(e.code!=='ENOENT')throw e}if(prior?.status==='prepared')throw Error('another archive transaction is unresolved');
const value={schema_version:1,transaction_id:'archive-txn-'+crypto.randomBytes(12).toString('hex'),change_name:change,status:'prepared',prepared_at:now,completed_at:null,target_path:target,log_path:log,root_snapshot_sha256:sha(fs.readFileSync(snapshotFile)),fingerprints,evidence_sha256:sha(fs.readFileSync(evidenceFile))},dir=path.dirname(file),tmp=path.join(dir,`.archive-transaction-${process.pid}-${Date.now()}-${crypto.randomBytes(3).toString('hex')}`),fd=fs.openSync(tmp,'wx',0o600);fs.writeFileSync(fd,JSON.stringify(value,null,2)+'\n');fs.fsyncSync(fd);fs.closeSync(fd);fs.renameSync(tmp,file);const dfd=fs.openSync(dir,'r');fs.fsyncSync(dfd);fs.closeSync(dfd);
NODE
node - "$transaction" "$(scripts/source_fingerprint.sh --kind source)" <<'NODE' || fail_archive 'source changed after archive transaction preparation'
const fs=require('fs'),[file,current]=process.argv.slice(2),x=JSON.parse(fs.readFileSync(file));if(x.status!=='prepared'||x.fingerprints?.source_fingerprint!==current)process.exit(1);
NODE
log_repo_state pre-archive-cli
set +e; scripts/openspec_cli.sh archive "$change" --yes --json >"$out" 2>"$err"; rc=$?; set -e; printf '\n[archive-cli]\nrc=%s\nstdout:\n' "$rc" >&3; cat "$out" >&3; printf '\nstderr:\n' >&3; cat "$err" >&3; [[ "$rc" -eq 0 ]] || fail_archive "OpenSpec archive exited $rc"
archived_as=$(node - "$out" "$change" "$target" <<'NODE'
const fs=require('fs'),path=require('path'),v=JSON.parse(fs.readFileSync(process.argv[2])),change=process.argv[3],target=path.resolve(process.argv[4]),a=v?.archive,expected=path.basename(target),names=['added','modified','removed','renamed'],totals=a?.totals;if(!a||typeof a!=='object'||a.change!==change||a.archivedAs!==expected||typeof a.path!=='string'||!path.isAbsolute(a.path)||path.resolve(a.path)!==target||a.specsUpdated!==true||!totals||typeof totals!=='object'||Array.isArray(totals)||Object.keys(totals).length!==names.length||names.some(k=>!Number.isInteger(totals[k])||totals[k]<0)||names.reduce((n,k)=>n+totals[k],0)<=0)process.exit(1);process.stdout.write(a.archivedAs);
NODE
) || fail_archive 'archive JSON contract mismatch'; [[ "$archived_as" != *'..'* && "$archived_as" != /* && "$archived_as" != *$'\n'* ]] || fail_archive 'archivedAs contains an unsafe path'; archived_dir="openspec/changes/archive/$archived_as"
[[ "$archived_dir" == "$target" && -d "$archived_dir" && ! -L "$archived_dir" && ! -e "$source_dir" && ! -L "$source_dir" && -f "$archived_dir/harness/evaluation.json" ]] || fail_archive 'archive path or retained evidence failed postcondition'
if [[ "$snapshot_schema" == 4 ]]; then [[ -f "$archived_dir/harness/integration-surface-report.json" && ! -L "$archived_dir/harness/integration-surface-report.json" ]] || fail_archive 'Integration Completeness report was not retained with the archived change'; fi
node - "$transaction" "$(scripts/source_fingerprint.sh --kind source)" <<'NODE' || fail_archive 'product source changed while OpenSpec archive was running'
const fs=require('fs'),[file,current]=process.argv.slice(2),x=JSON.parse(fs.readFileSync(file));if(x.status!=='prepared'||x.fingerprints?.source_fingerprint!==current)process.exit(1);
NODE
scripts/openspec_cli.sh validate --specs --strict --json --no-interactive > "$val" || fail_archive 'main specs strict validation failed'
node - "$val" <<'NODE' || fail_archive 'main spec validation JSON has errors'
const fs=require('fs'),v=JSON.parse(fs.readFileSync(process.argv[2])),items=v?.items,failed=v?.summary?.totals?.failed;function hasError(x){if(!x||typeof x!=='object')return false;if(Array.isArray(x.issues)&&x.issues.some(i=>String(i?.level||'').toUpperCase()==='ERROR'))return true;return Object.values(x).some(hasError)}if(!Array.isArray(items)||items.some(x=>x?.valid!==true)||!Number.isInteger(failed)||failed!==0||hasError(v))process.exit(1);
NODE
node - "$change" "$archived_as" <<'NODE' || fail_archive 'archive succeeded but active snapshot finalization failed'
const fs=require('fs'),path=require('path');const [c,a]=process.argv.slice(2),f='ai_snapshot.json',d=JSON.parse(fs.readFileSync(f));if(d.active_change!==c)process.exit(4);d.active_change=null;d.phase='idle';d.current_step='change-archived';d.next_step='Create or select the next change';delete d.archive_failure;d.last_archived_change={change_name:c,archived_as:a,archived_at:new Date().toISOString().replace('.000Z','Z')};d.updated_at=d.last_archived_change.archived_at;let t;for(let i=0;i<20;i++){t=path.join(path.dirname(f),`.snapshot-archive-success-${process.pid}-${i}`);try{const fd=fs.openSync(t,'wx',0o644);fs.writeFileSync(fd,JSON.stringify(d,null,2)+'\n');fs.fsyncSync(fd);fs.closeSync(fd);fs.renameSync(t,f);const dir=fs.openSync(path.dirname(f)||'.','r');fs.fsyncSync(dir);fs.closeSync(dir);t=null;break}catch(e){if(e.code!=='EEXIST')throw e}}if(t)throw Error('cannot allocate atomic snapshot temp');
NODE
node - "$transaction" "$change" committed <<'NODE' || fail_archive 'archive succeeded but transaction journal could not be committed'
const fs=require('fs'),path=require('path'),crypto=require('crypto');const [file,change,status]=process.argv.slice(2),st=fs.lstatSync(file),x=JSON.parse(fs.readFileSync(file));if(!st.isFile()||st.isSymbolicLink()||x.change_name!==change||x.status!=='prepared'||status!=='committed')process.exit(1);x.status=status;x.completed_at=new Date().toISOString().replace('.000Z','Z');const dir=path.dirname(file),tmp=path.join(dir,`.archive-transaction-${process.pid}-${Date.now()}-${crypto.randomBytes(3).toString('hex')}`),fd=fs.openSync(tmp,'wx',0o600);fs.writeFileSync(fd,JSON.stringify(x,null,2)+'\n');fs.fsyncSync(fd);fs.closeSync(fd);fs.renameSync(tmp,file);const dfd=fs.openSync(dir,'r');fs.fsyncSync(dfd);fs.closeSync(dfd);
NODE
node - "$archived_dir/harness/archive-receipt.json" "$change" "$archived_as" "$fp" "$out" "$val" <<'NODE' || fail_archive 'archive succeeded but its retained receipt could not be written'
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const [file,change,archivedAs,fpFile,archiveOutput,validationOutput]=process.argv.slice(2),sha=b=>'sha256:'+crypto.createHash('sha256').update(b).digest('hex'),fingerprints=JSON.parse(fs.readFileSync(fpFile));
if(!/^sha256:[0-9a-f]{64}$/.test(fingerprints.profile_sha256||''))throw Error('profile fingerprint missing');
const value={schema_version:1,change_name:change,archived_as:archivedAs,archived_at:new Date().toISOString().replace('.000Z','Z'),profile_sha256:fingerprints.profile_sha256,source_fingerprint:fingerprints.source_fingerprint,artifact_fingerprint:fingerprints.artifact_fingerprint,base_specs_fingerprint_before:fingerprints.base_specs_fingerprint,archive_output_sha256:sha(fs.readFileSync(archiveOutput)),main_specs_validation_sha256:sha(fs.readFileSync(validationOutput)),authority:'retained-receipt-not-active-state'};
const dir=path.dirname(file),st=fs.lstatSync(dir);if(!st.isDirectory()||st.isSymbolicLink()||fs.existsSync(file))throw Error('unsafe archive receipt destination');const temp=path.join(dir,`.archive-receipt-${process.pid}-${crypto.randomBytes(4).toString('hex')}`);fs.writeFileSync(temp,JSON.stringify(value,null,2)+'\n',{mode:0o644,flag:'wx'});fs.renameSync(temp,file);
NODE
printf '\n[success]\narchived_as=%s\ncompleted_at=%s\n' "$archived_as" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >&3; log_repo_state post-success; echo "Archived $change as $archived_as"
