#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/harness_lock.sh"
change=; as_json=0; context_role=; context_task=
while [[ $# -gt 0 ]]; do case "$1" in --json) as_json=1 ;; --agent-context) context_role=${2:?}; shift ;; --task) context_task=${2:?}; shift ;; *) [[ -z "$change" ]] || exit 2; change=$1 ;; esac; shift; done
[[ -z "$context_role" || "$context_role" =~ ^(investigator|reviewer|generator)$ ]] || exit 2; [[ -z "$context_task" || "$context_task" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit 2; [[ -z "$context_role" || "$context_role" == generator || -z "$context_task" ]] || { echo '[ERR] --task is only valid for Generator context' >&2; exit 2; }; [[ "$context_role" != generator || -n "$context_task" ]] || { echo '[ERR] Generator context requires --task' >&2; exit 2; }
requested=$change; [[ -z "$requested" ]] || harness_validate_change_id "$requested"; harness_lock_acquire change-status "$requested"; active=$(harness_active_optional)
if [[ -n "$requested" ]]; then harness_validate_change_id "$requested"; change=$requested; elif [[ -n "$active" ]]; then harness_validate_change_id "$active"; change=$active; else echo '[ERR] no active change; pass an explicit change ID to inspect' >&2; exit 4; fi
harness_lock_bind_change "$change"; [[ -d "openspec/changes/$change" && ! -L "openspec/changes/$change" && -d "openspec/changes/$change/harness" && ! -L "openspec/changes/$change/harness" ]] || { echo "[ERR] stale or archived change: $change" >&2; exit 4; }
s=$(mktemp); a=$(mktemp); combined=$(mktemp); recheck_log=$(mktemp); trap 'rm -f -- "$s" "$a" "$combined" "$recheck_log"; harness_lock_release' EXIT
scripts/openspec_cli.sh status --change "$change" --json > "$s" || { echo '[ERR] OpenSpec status failed' >&2; exit 6; }
scripts/openspec_cli.sh instructions apply --change "$change" --json > "$a" || { echo '[ERR] OpenSpec instructions failed' >&2; exit 6; }
current_base=$(scripts/source_fingerprint.sh --kind base-specs --change "$change")
current_change=; current_policy=; current_integration=; local_version=$(node -p "JSON.parse(require('fs').readFileSync(process.argv[1])).schema_version" "openspec/changes/$change/harness/ai_snapshot.json" 2>/dev/null || true)
if [[ "$local_version" == 3 || "$local_version" == 4 ]]; then
  planning_json=$(scripts/source_fingerprint.sh --kind planning --change "$change" --json) || { echo '[ERR] planning/TDD/integration policy fingerprint failed' >&2; exit 6; }
  current_change=$(node -e 'const fs=require("fs"),x=JSON.parse(fs.readFileSync(0,"utf8"));process.stdout.write(x.planning_fingerprint)' <<<"$planning_json")
  current_policy=$(node -e 'const fs=require("fs"),x=JSON.parse(fs.readFileSync(0,"utf8"));process.stdout.write(x.tdd_policy_sha256)' <<<"$planning_json")
  if [[ "$local_version" == 4 ]]; then current_integration=$(node -e 'const fs=require("fs"),x=JSON.parse(fs.readFileSync(0,"utf8"));if(!/^sha256:[0-9a-f]{64}$/.test(x.integration_completeness_sha256||""))process.exit(6);process.stdout.write(x.integration_completeness_sha256)' <<<"$planning_json") || { echo '[ERR] Integration Completeness planning digest failed' >&2; exit 6; }; fi
fi
evaluation_fresh=0; baseline_status=$(node - "openspec/changes/$change/harness/evaluation-baseline.json" <<'NODE' 2>/dev/null || true
const fs=require('fs'),f=process.argv[2];if(!fs.existsSync(f))process.exit(0);const x=JSON.parse(fs.readFileSync(f));if(typeof x.status==='string')process.stdout.write(x.status);
NODE
)
if [[ "$baseline_status" == complete ]]; then
  token=${AUTOAI_LOCK_TOKEN:-$HARNESS_OWNED_TOKEN}
  if AUTOAI_LOCK_TOKEN="$token" AUTOAI_PARENT_PURPOSE=change-status scripts/evaluator_check.sh --recheck "$change" >"$recheck_log" 2>&1; then evaluation_fresh=1; fi
fi
node - "$change" "$s" "$a" "$active" "$current_base" "$current_change" "$current_policy" "$current_integration" "openspec/changes/$change/harness" "$evaluation_fresh" ai_snapshot.json <<'NODE' > "$combined"
const fs=require('fs'),cp=require('child_process');const [c,s,a,active,currentBase,currentChange,currentPolicy,currentIntegration,h,recheck,rootFile]=process.argv.slice(2),fail=m=>{throw Error(m)},read=p=>{if(!fs.existsSync(p))return null;const st=fs.lstatSync(p);if(!st.isFile()||st.isSymbolicLink())fail('unsafe evidence file: '+p);return JSON.parse(fs.readFileSync(p))},status=JSON.parse(fs.readFileSync(s)),instructions=JSON.parse(fs.readFileSync(a)),root=read(rootFile),local=read(h+'/ai_snapshot.json'),verification=read(h+'/verification.json'),footprint=read(h+'/change-footprint.json'),surfaceReport=read(h+'/integration-surface-report.json'),baseline=read(h+'/evaluation-baseline.json'),evaluation=read(h+'/evaluation.json');
const required=['proposal','design','specs','tasks'];if(status?.changeName!==c||status?.schemaName!=='spec-driven'||typeof status?.isComplete!=='boolean'||!Array.isArray(status?.artifacts)||status.artifacts.length!==required.length)fail('status JSON contract mismatch');const artifacts=new Map;for(const x of status.artifacts){if(!x||typeof x.id!=='string'||artifacts.has(x.id)||!required.includes(x.id)||!['blocked','ready','done'].includes(x.status))fail('status artifact contract mismatch');artifacts.set(x.id,x.status)}if(required.some(x=>!artifacts.has(x))||status.isComplete!==required.every(x=>artifacts.get(x)==='done'))fail('status completion mismatch');
const p=instructions?.progress,t=instructions?.tasks;if(instructions?.changeName!==c||instructions?.schemaName!=='spec-driven'||!['blocked','ready','all_done'].includes(instructions?.state)||!p||!Number.isInteger(p.total)||!Number.isInteger(p.complete)||!Number.isInteger(p.remaining)||p.total<0||p.complete<0||p.complete>p.total||p.remaining!==p.total-p.complete||!Array.isArray(t)||t.length!==p.total)fail('instructions JSON contract mismatch');const ids=new Set;let done=0;for(const x of t){if(!x||typeof x.id!=='string'||!x.id||ids.has(x.id)||typeof x.done!=='boolean')fail('instructions task contract mismatch');ids.add(x.id);if(x.done)done++}if(done!==p.complete||instructions.state==='ready'&&p.remaining===0||instructions.state==='all_done'&&(p.total===0||p.remaining!==0)||instructions.state==='blocked'&&p.total!==0)fail('instructions state mismatch');
if(!local||![2,3,4].includes(local.schema_version)||'active_change'in local)fail('local snapshot contract mismatch');const recorded=local.planned_base_specs_fingerprint||null,baseFresh=!!recorded&&recorded===currentBase,changeFresh=local.schema_version===2?true:!!local.planned_change_fingerprint&&local.planned_change_fingerprint===currentChange&&!!local.planned_tdd_policy_sha256&&local.planned_tdd_policy_sha256===currentPolicy,integrationFresh=local.schema_version!==4?true:!!local.planned_integration_completeness_sha256&&local.planned_integration_completeness_sha256===currentIntegration,plannedFresh=baseFresh&&changeFresh&&integrationFresh,base=local.implementation_base_commit||null,familySupported=local.schema_version===2&&verification?.schema_version===1||local.schema_version===3&&verification?.schema_version===2||local.schema_version===4&&verification?.schema_version===3,upgradeRequired=!familySupported;let baseValid=base?false:null,baseReason=base?'invalid commit':'not frozen';if(base){if(typeof base!=='string'||!/^[0-9a-f]{40,64}$/.test(base))baseReason='not a full commit ID';else try{const resolved=cp.execFileSync('git',['rev-parse','--verify',base+'^{commit}'],{encoding:'utf8'}).trim();if(resolved!==base)baseReason='commit ID does not resolve exactly';else{cp.execFileSync('git',['merge-base','--is-ancestor',base,'HEAD']);baseValid=true;baseReason=null}}catch{baseValid=false;baseReason='commit missing or not an ancestor of HEAD'}}
const evalFresh=recheck==='1',verdict=evaluation?.verdict||null,archiveFailed=c===active&&root?.active_change===c&&root?.phase==='archive_failed'&&root?.archive_failure?.change===c;let phase='planning';if(archiveFailed)phase='archive_failed';else if(upgradeRequired)phase='evidence_upgrade_required';else if(recorded&&!plannedFresh)phase='plan_revision_required';else if(base&&!baseValid)phase='implementation_base_invalid';else if(baseline?.status==='in_progress')phase='evaluation_in_progress';else if(baseline?.status==='complete'){if(!evalFresh)phase=baseValid&&instructions.state==='ready'?'implementing':'evaluation_stale';else if(verdict==='Pass')phase='accepted';else if(verdict==='Fail')phase='evaluation_failed';else if(verdict==='Blocked')phase='evaluation_blocked';else phase='evaluation_stale'}else if(baseValid&&instructions.state==='all_done')phase='awaiting_evaluation';else if(baseValid)phase='implementing';else if(plannedFresh&&status.isComplete)phase='plan_ready';
const projectCommandEvidence=fs.existsSync(h+'/project-command-evidence'),changeRoot=`openspec/changes/${c}`,mustRead=['PROJECT_ATTRIBUTION.md','CLAUDE.md','AGENTS.md','docs/ai/openspec.md','docs/ai/workflow.md','docs/ai/testing.md',`${changeRoot}/proposal.md`,`${changeRoot}/design.md`,`${changeRoot}/tasks.md`,`${changeRoot}/specs/`,`${h}/ai_snapshot.json`,`${h}/verification.json`,...(projectCommandEvidence?[`${h}/project-command-evidence/`]:[]),...(footprint?[`${h}/change-footprint.json`]:[]),...(surfaceReport?[`${h}/integration-surface-report.json`]:[]),...(baseline?[`${h}/evaluation-baseline.json`]:[]),...(evaluation?[`${h}/evaluation.json`]:[])];
console.log(JSON.stringify({schema_version:2,change_name:c,active:c===active,derived_phase:phase,evidence_upgrade_required:upgradeRequired,planning_artifacts_ready:status.isComplete,status,instructions,planned_base:{recorded,current:currentBase,fresh:baseFresh},planned_change:{recorded:local.planned_change_fingerprint||null,current:currentChange||null,policy_recorded:local.planned_tdd_policy_sha256||null,policy_current:currentPolicy||null,integration_recorded:local.planned_integration_completeness_sha256||null,integration_current:currentIntegration||null,integration_fresh:integrationFresh,fresh:changeFresh&&integrationFresh},implementation_base:{recorded:base,valid:baseValid,reason:baseReason},footprint,integration_surface_report:surfaceReport,must_read:mustRead,archive_failure:archiveFailed?root.archive_failure:null,evaluation_baseline:baseline,evaluation:evaluation?{evaluation_id:evaluation.evaluation_id||null,verdict,evaluated_at:evaluation.evaluated_at||null,fresh:evalFresh}:null},null,2));
NODE
if [[ -n "$context_role" ]]; then
  node - "$combined" "$context_role" "$context_task" <<'NODE'
const fs=require('fs'),[file,role,taskId]=process.argv.slice(2),x=JSON.parse(fs.readFileSync(file)),tasks=x.instructions.tasks||[];if(role==='generator'){const t=tasks.find(v=>v.id===taskId);if(!x.active||x.derived_phase!=='implementing'||!x.planned_base.fresh||!x.planned_change.fresh||!x.implementation_base.valid||!t||t.done)throw Error('Generator context requires active/fresh implementing state and an unchecked task')}if(role==='reviewer'&&(!x.implementation_base.valid||!x.footprint))throw Error('Reviewer context requires a frozen implementation base and footprint evidence');const readOnly=role!=='generator',rolePrompt=role==='generator'?'prompts/generator.md':role==='reviewer'?'prompts/evaluator.md':'prompts/resume.md',required=[...new Set([...(x.must_read||[]),rolePrompt])],reviewCommands=role==='reviewer'?[['git','diff','--no-renames',x.implementation_base.recorded,'HEAD','--'],['git','diff','--cached','--no-renames','--'],['git','diff','--no-renames','--'],['git','ls-files','--others','--exclude-standard','-z']]:[],out={schema_version:1,change_name:x.change_name,task_id:taskId||null,role,context_mode:readOnly?'fresh-read-only':'fresh-generator',source_of_truth:'OpenSpec',active_required:role==='generator',required_files:required,required_read_only_commands:reviewCommands,write_scope:readOnly?[]:['approved product/test paths for the selected task'],forbidden_actions:['switch active change','modify proposal/design/specs/budget/TDD/Integration policy','write final Evaluation','archive','perform Git integration or cleanup',...(readOnly?['modify code, tests, tasks or evidence']:[])],trust_boundary:role==='reviewer'?'Read the actual committed, staged, unstaged, untracked and gitlink state plus every surface report candidate; never rely on Generator summaries alone.':null,fingerprints:{planned_base:x.planned_base,planned_change:x.planned_change,implementation_base:x.implementation_base},task:taskId?tasks.find(v=>v.id===taskId):null};console.log(JSON.stringify(out,null,2));
NODE
elif [[ "$as_json" -eq 1 ]]; then cat "$combined"; else node - "$combined" <<'NODE'
const fs=require('fs'),x=JSON.parse(fs.readFileSync(process.argv[2])),base=x.implementation_base;console.log(`Change: ${x.change_name}\nActive: ${x.active?'yes':'no'}\nDerived phase: ${x.derived_phase}\nPlanning artifacts ready: ${x.planning_artifacts_ready?'yes':'no'}\nPlanned base fresh: ${x.planned_base.fresh?'yes':'no'}\nImplementation base: ${base.recorded?(base.valid?'valid':'invalid'):'not frozen'}\nFootprint: ${x.footprint?.status||'not generated'}\nIntegration surface report: ${x.integration_surface_report?.status||'not generated'}\nEvaluation: ${x.evaluation?(x.evaluation.verdict+' / '+(x.evaluation.fresh?'fresh':'stale')):x.evaluation_baseline?.status||'not started'}\nMust read:\n- ${(x.must_read||[]).join('\n- ')}`);
NODE
fi
