#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),lib=require('./project_profile_lib.js');
const args=process.argv.slice(2);if(args.length<2){console.error('usage: event_audit.sh <change> --refresh|--check [--json]');process.exit(2)}
const change=args.shift(),refresh=args.includes('--refresh'),check=args.includes('--check'),json=args.includes('--json'),validChange=value=>typeof value==='string'&&/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(value)&&value!=='archive'&&!value.startsWith('archive-')&&value!=='stale'&&!value.startsWith('stale-');if(!validChange(change)||refresh===check||args.some(x=>!['--refresh','--check','--json'].includes(x))){console.error('[ERR] invalid event audit arguments');process.exit(2)}
const root=lib.ensureRepositoryRoot(process.cwd()),sha=v=>'sha256:'+crypto.createHash('sha256').update(v).digest('hex');
function resolve(){const activeRelative=`openspec/changes/${change}`,active=path.join(root,...activeRelative.split('/'));if(fs.existsSync(active))return {root:lib.safeRepositoryEntry(root,activeRelative,'active audit change','directory').path,key:change};const archive=lib.safeRepositoryEntry(root,'openspec/changes/archive','audit archive','directory').path,escaped=change.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),matches=fs.readdirSync(archive).filter(x=>new RegExp('^\\d{4}-\\d{2}-\\d{2}-'+escaped+'$').test(x));if(matches.length!==1)throw Error('change is missing or archived identity is ambiguous');const relative='openspec/changes/archive/'+matches[0];return {root:lib.safeRepositoryEntry(root,relative,'archived audit change','directory').path,key:matches[0]}}
function regular(file){const relative=path.relative(root,file).split(path.sep).join('/');return fs.readFileSync(lib.safeRepositoryEntry(root,relative,'audit source','file').path)}
function events(base){
  const sources=[];for(const rel of ['harness/ai_snapshot.json','harness/verification.json','harness/evaluation-baseline.json','harness/evaluation.json','harness/archive-receipt.json']){const file=path.join(base,rel);if(fs.existsSync(file))sources.push({rel,bytes:regular(file)})}
  const history=path.join(base,'harness','evaluations');if(fs.existsSync(history)){const s=fs.lstatSync(history);if(!s.isDirectory()||s.isSymbolicLink())throw Error('unsafe evaluation history');for(const name of fs.readdirSync(history).sort())sources.push({rel:'harness/evaluations/'+name,bytes:regular(path.join(history,name))})}
  const projectCommands=path.join(base,'harness','project-command-evidence');if(fs.existsSync(projectCommands)){const s=fs.lstatSync(projectCommands);if(!s.isDirectory()||s.isSymbolicLink())throw Error('unsafe Project Command evidence history');for(const name of fs.readdirSync(projectCommands).sort()){if(!/^[0-9a-f]{64}\.json$/.test(name))throw Error('unexpected Project Command evidence entry');sources.push({rel:'harness/project-command-evidence/'+name,bytes:regular(path.join(projectCommands,name))})}}
  sources.sort((a,b)=>Buffer.from(a.rel).compare(Buffer.from(b.rel)));let previous=null;const eventTypes=new Set(['ai_snapshot','verification','evaluation-baseline','evaluation','archive-receipt','evaluation-terminal','project-command']);
  return sources.map((source,index)=>{let value={};try{value=JSON.parse(source.bytes)}catch{}const when=value.evaluated_at||value.completed_at||value.aborted_at||value.finished_at||value.archived_at||value.planning_approved_at||'1970-01-01T00:00:00.000Z',type=source.rel.includes('/evaluations/')?'evaluation-terminal':source.rel.includes('/project-command-evidence/')?'project-command':source.rel.split('/').pop().replace(/\.json$/,'');if(!eventTypes.has(type))throw Error('unrecognized audit event type: '+type);const record={schema_version:1,event_id:sha(Buffer.from(change+'\0'+source.rel)),change_id:change,type,occurred_at:when,source_path:source.rel,source_sha256:sha(source.bytes),summary:{schema_version:value.schema_version??null,status:value.status??null,verdict:value.verdict??null},previous_event_sha256:previous,event_sha256:null};record.event_sha256=sha(Buffer.from(JSON.stringify({...record,event_sha256:null})));previous=record.event_sha256;return record});
}
try{
  const resolved=resolve();
  const target=path.join(root,'.ai-harness','derived','audit',resolved.key+'.jsonl'),body=events(resolved.root).map(x=>JSON.stringify(x)).join('\n')+'\n';
  if(refresh){const dir=lib.ensureRepositoryDirectory(root,'.ai-harness/derived/audit','audit output directory');if(path.dirname(target)!==dir)throw Error('audit target escaped its derived directory');if(fs.existsSync(target))lib.safeRepositoryEntry(root,path.relative(root,target).split(path.sep).join('/'),'audit target','file');const temp=path.join(dir,`.audit-${process.pid}-${crypto.randomBytes(4).toString('hex')}`);fs.writeFileSync(temp,body,{mode:0o600,flag:'wx'});lib.safeRepositoryEntry(root,'.ai-harness/derived/audit','audit output directory','directory');fs.renameSync(temp,target)}else{const actual=regular(target);if(!actual.equals(Buffer.from(body)))throw Error('derived event audit is stale or corrupt')}
  const result={schema_version:1,status:'fresh',path:path.relative(root,target).split(path.sep).join('/'),event_count:body.trim()?body.trim().split('\n').length:0,authority:'derived-rebuildable-not-a-state-source'};if(json)console.log(JSON.stringify(result,null,2));else console.log(`[OK] event audit ${result.path}: ${result.event_count} events`);
}catch(error){console.error('[ERR] '+error.message);process.exit(6)}
