#!/usr/bin/env bash
set -euo pipefail
scripts/attribution_check.sh --quiet || { echo '[ERR] project attribution contract is invalid; repair it before resuming managed work' >&2; exit 6; }
source "$(dirname "$0")/harness_lock.sh"; harness_lock_acquire resume ""; active=$(harness_active_optional); [[ -z "$active" ]] || harness_lock_bind_change "$active"
if [[ -z "$active" ]]; then echo 'No active change. Select or create one explicitly.'; exit 0; fi
harness_validate_change_id "$active"; [[ -d "openspec/changes/$active" && ! -L "openspec/changes/$active" ]] || { echo "[ERR] stale or archived active pointer: $active; inspect then clear explicitly" >&2; exit 4; }
dynamic=$(mktemp "${TMPDIR:-/tmp}/autoai-resume.XXXXXX"); trap 'rm -f -- "$dynamic"; harness_lock_release' EXIT
AUTOAI_LOCK_TOKEN="$HARNESS_OWNED_TOKEN" AUTOAI_PARENT_PURPOSE=resume scripts/change_status.sh "$active" --json > "$dynamic" || { echo '[ERR] active change status could not be rebuilt; cached recovery state was not trusted' >&2; exit 6; }
node - "$dynamic" <<'NODE'
const fs=require('fs'),x=JSON.parse(fs.readFileSync(process.argv[2])),base=x.implementation_base,report=x.integration_surface_report;console.log(`Active change: ${x.change_name}\nDerived phase: ${x.derived_phase}\nPlanning artifacts ready: ${x.planning_artifacts_ready?'yes':'no'}\nPlanned baseline: ${x.planned_base.fresh?'fresh':x.planned_base.recorded?'stale':'not frozen'}\nImplementation base: ${base.recorded?(base.valid?'valid':'invalid — '+base.reason):'not frozen'}\nTask progress: ${x.instructions.progress.complete}/${x.instructions.progress.total}\nIntegration surface report: ${report?(report.status+' — mandatory reading before review/Evaluation'):'not generated'}\nEvaluation: ${x.evaluation?(x.evaluation.verdict+' / '+(x.evaluation.fresh?'fresh':'stale')):x.evaluation_baseline?.status||'not started'}\nMust read:\n- ${(x.must_read||[]).join('\n- ')}\nNext cursor: ${x.derived_phase==='plan_revision_required'?'return to Planner and re-approve changed planning/Integration artifacts':x.derived_phase==='implementation_base_invalid'?'stop and recover a valid implementation base':x.derived_phase==='evaluation_stale'?'recheck the surface report and rerun independent Evaluation':x.derived_phase==='awaiting_evaluation'&&!report?'generate and review integration-surface-report.json before Evaluation':x.derived_phase}`);
NODE
phase=$(node -p "JSON.parse(require('fs').readFileSync(process.argv[1])).derived_phase" "$dynamic")
case "$phase" in evidence_upgrade_required|plan_revision_required|implementation_base_invalid) echo "[ERR] recovery gate: $phase" >&2; exit 6 ;; esac
